//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPLIn.WebParts {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Web.UI;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Web.UI.WebControls;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class PeopleSearchRefiner {
        
        public static implicit operator global::System.Web.UI.TemplateControl(PeopleSearchRefiner target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::SPLIn.WebParts.PeopleSearchRefiner @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"

<script type=""text/javascript"">
    function showPeopleSearchRefiners(result) {
        var facetsHTML = """";
        for (var facetIndex in result.facets.values) {
            var facet = result.facets.values[facetIndex];
            facetsHTML += '     <div class=""ms-searchref-categoryname"">' + facet.name + '</div>';
            facetsHTML += '     <ul class=""ms-searchref-filters"">';
            for (var bucketIndex in facet.buckets.values) {
                var bucket = facet.buckets.values[bucketIndex];
                facetsHTML += '     <li class=""ms-searchref-filter ms-searchref-' + (bucket.selected ? 'selected' : 'unselected') + '"">';
                facetsHTML += '         <a class=""ms-searchref-filterlink"" title=""Refine By: ' + bucket.name + '"" href=javascript:loadPeopleSearchData(""' + facet.code + '"",""' + bucket.code + '"")>' + bucket.name + '</a>';
                facetsHTML += '         <span class=""ms-searchref-count"">(' + bucket.count + ')</span>';
                facetsHTML += '     </li>';
            }
            facetsHTML += '     </ul>';
            facetsHTML += '     <div class=""ms-searchref-catseparator""> </div>';
        }

        $(""#SPLInPeopleRefiners"").html(facetsHTML);
    }

    function getPeopleSearchRefinerFields() {
        return ""facets:(");
                @__w.Write( RefinerFields );

            @__w.Write(")\";\r\n    }\r\n\r\n    function getPeopleSearchRefiners() {\r\n        return \"facets=");
               @__w.Write( Refiners );

            @__w.Write(@""";
    }
</script>

<div id=""SPLInPeopleRefiners"" class=""srch-WPBody ms-searchref-main"">
    <div class=""ms-searchref-categoryname""></div>
    <ul class=""ms-searchref-filters"">
        <li class=""ms-searchref-filtermsg"">
            <span class=""ms-searchref-filterlink ms-searchref-msg"">No refinements available</span>
        </li>
    </ul>
</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
