//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPLIn.WebParts {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System;
    using System.Collections;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Web.UI;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Web.UI.WebControls;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class PeopleSearchBox {
        
        public static implicit operator global::System.Web.UI.TemplateControl(PeopleSearchBox target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::SPLIn.WebParts.PeopleSearchBox @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<script type=\"text/javascript\" src=\"http://platform.linkedin.com/in.js\">\r\n   " +
                    " api_key: ");
     @__w.Write( LinkedInApiKey );

            @__w.Write("\r\n    authorize: ");
       @__w.Write( RememberMe.ToString().ToLower() );

            @__w.Write(@"
</script>

<script src=""http://code.jquery.com/jquery.js"" type=""text/javascript""></script>
 
<script type=""text/javascript"">
    function loadPeopleSearchData(facetCode, bucketCode) {
        var searchQuery = $(""#SPLInSearchBox"").val();
        if (searchQuery == """") {
            return;
        }

        if (!IN.API) {
            alert(""Please set the LinkedIn API Key web part property"");
            return;
        }

        var url = ""/people-search:(people:(");
                                   @__w.Write( DataFields );

            @__w.Write(")\";\r\n\r\n        if (typeof getPeopleSearchRefinerFields == \'function\') {\r\n        " +
                    "    url += \",\" + getPeopleSearchRefinerFields();\r\n        }\r\n\r\n        url += \")" +
                    "?keywords=\" + searchQuery;\r\n\r\n        if (typeof getPeopleSearchRefiners == \'fun" +
                    "ction\') {\r\n            url += \"&\" + getPeopleSearchRefiners();\r\n        }\r\n\r\n   " +
                    "     if (facetCode && bucketCode) {\r\n            url += \"&facet=\" + facetCode + " +
                    "\",\" + bucketCode;\r\n        }\r\n\r\n        if (typeof getPeopleSearchResultCount ==" +
                    " \'function\') {\r\n            url += \"&\" + getPeopleSearchResultCount();\r\n        " +
                    "}\r\n\r\n        IN.API.Raw(url).result(function (result) {\r\n            if (typeof " +
                    "showPeopleSearchResults == \'function\') {\r\n                showPeopleSearchResult" +
                    "s(result);\r\n            }\r\n            if (typeof showPeopleSearchRefiners == \'f" +
                    "unction\') {\r\n                showPeopleSearchRefiners(result);\r\n            }\r\n " +
                    "           if (typeof showPeopleSearchStatistics == \'function\') {\r\n             " +
                    "   showPeopleSearchStatistics(result);\r\n            } \r\n        })\r\n        .err" +
                    "or(function (error) {\r\n            if (error.status === 401) {\r\n                " +
                    "// try it again\r\n                var oldToken = IN.ENV.auth.oauth_token;\r\n      " +
                    "          IN.User.refresh();\r\n                // since the refresh method is asy" +
                    "nchronous but doesn\'t provide a callback, we have to poll\r\n                funct" +
                    "ion tryAgain() {\r\n                    setTimeout(function () {\r\n                " +
                    "        if (oldToken !== IN.ENV.auth.oauth_token) {\r\n                           " +
                    " loadPeopleSearchData();\r\n                        }\r\n                        els" +
                    "e {\r\n                            setTimeout(tryAgain, 100);\r\n                   " +
                    "     }\r\n                    }, 100);\r\n                }\r\n                tryAgai" +
                    "n();\r\n            }\r\n        });\r\n    }\r\n\r\n    $(document).ready(function () {\r\n" +
                    "        $(\'#SPLInSearchBox\').bind(\'keypress\', function (e) {\r\n            if (e." +
                    "keyCode == 13) {\r\n                e.preventDefault();\r\n                loadPeopl" +
                    "eSearchData();\r\n            }\r\n        });\r\n    });\r\n</script>\r\n\r\n<div>\r\n    <ta" +
                    "ble class=\"ms-sbtable ms-sbtable-ex\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                    "\r\n        <tr class=\"ms-sbrow\">\r\n            <td class=\"ms-sbcell\">\r\n           " +
                    "     <input type=\"text\" name=\"SPLInSearchBox\" id=\"SPLInSearchBox\" class=\"ms-sbpl" +
                    "ain\" style=\"margin:0px; width:368px;\" />\r\n            </td>\r\n            <td cla" +
                    "ss=\"ms-sbgo ms-sbcell\">\r\n                <a href=\"javascript:loadPeopleSearchDat" +
                    "a()\"><img style=\"border-width:0px;\" class=\"srch-gosearchimg\" onmouseover=\"this.s" +
                    "rc=\'\\u002f_layouts\\u002fimages\\u002fgosearchhover30.png\'\" onmouseout=\"this.src=\'" +
                    "\\u002f_layouts\\u002fimages\\u002fgosearch30.png\'\" src=\"/_layouts/images/gosearch3" +
                    "0.png\" /></a>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
